version: "3"

services:
  restorix:
    image: specialaro/restorix:latest
    container_name: restorix
    restart: "no"
    environment:
      # RESTORIX MODE: backup OR restore
      - MODE_ENV=restore
      - CRONTAB_ENV=* * * * *
      # OPTIONAL SETTINGS
      # ----------------------------------------

      # SCP SSH SETTINGS
      # If you want to use SCP uncomment the next for lines (all must have values, otherwise it will fail)
      # - SSH_HOST_ENV=
      # - SSH_USERNAME_ENV=
      # - SSH_PASSWORD_ENV=
      # - SSH_PATH_ENV=

      # FILENAME FOR BACKUP / RESTORE FILENAME
      # DEFAULT: output
      # - FILENAME_ENV=testing

      # MAX FILESIZE OF BACKUP
      # Will split into multiple files of the defined size (in MB or KB)
      # DEFAULT: 4000m (4GB)
      # Example: 300m or 100k
      # - MAX_FILESIZE_ENV=1k

      # ----------------------------------------

    volumes:
      # LIST OF VOLUMES TO BACKUP
      # ----------------------------------------
      - teste:/tobackup/teste:ro
      # - portainer_data:/tobackup/portainer_data:ro
      # ----------------------------------------

      # OUTPUT FOLDER WITH THE BACKUPS
      # ----------------------------------------
      - ./backup:/backup
      # ----------------------------------------

      # DO NOT DELETE THE NEXT LINE
      - /var/run/docker.sock:/var/run/docker.sock

# LIST OF VOLUMES TO BACKUP
# Please always use "external: true" otherwise it can fail
# --------------------------------------------------------
volumes:
  teste:
    external: true
  portainer_data:
    external: true
# --------------------------------------------------------
